version: "3"
services:
  app:
    container_name: go-test
    build:
      context: .
      dockerfile: ./infra/Dockerfile
    tty: true
    volumes:
      - ./app:/go/src
    env_file:
      - ./.go_env
    ports:
      - 8080:8080
